# Generated by Django 5.1.1 on 2024-10-21 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_date_created_ticket_time_created_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
