# Generated by Django 5.1.1 on 2024-10-26 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_userfollows'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='body',
            new_name='commentaire',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='headline',
            new_name='titre',
        ),
    ]
