# Generated by Django 5.1.1 on 2024-10-28 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_ticket_time_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='commentaire',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='titre',
            new_name='headline',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='note',
            new_name='rating',
        ),
    ]
