# Generated by Django 5.1.1 on 2024-10-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
    ]
