# Generated by Django 5.1.1 on 2024-10-29 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20241028_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(limit_choices_to={'CREATOR', 'role'}, to=settings.AUTH_USER_MODEL, verbose_name='suit'),
        ),
    ]
